Fix `git-update-pr` to work with `push.default = nothing`

diff --git a/dot_local/bin/executable_git-update-pr b/dot_local/bin/executable_git-update-pr
--- a/dot_local/bin/executable_git-update-pr
+++ b/dot_local/bin/executable_git-update-pr
@@ -79,7 +79,7 @@ if ! git -C "$worktree_dir" cherry-pick "$new_refspec^..$base_refspec"; then
   git -C "$worktree_dir" cherry-pick --continue
 fi
 
-git -C "$worktree_dir" push --quiet || echo "warning: failed to push '$branch_name'" >&2
+git -C "$worktree_dir" push "$remote_name" "$remote_branch_name" --quiet || echo "warning: failed to push '$branch_name'" >&2
 
 _checkout_empty
 
